### ISSUE TITLE
Symbol list

### ISSUE THREAD

**Issue by jaikumarm** [rpongcha/MachineLearningProject#1]
Can you please post full asset list with symbols and full names and possibly the CME equivalent.

I read through the paper and searched the web cant find an actual list. there is one chart in the paper that shows the list as labels, but it only has 42 symbols and some of the two letter symbols do not match with anything in CME website.

**Comment by mfrdixon** [comment]
Hi there!

Thanks for your interest in our work. Unfortunately, the symbols were
provided by a hedge fund who use their own symbol naming convention.  We
have reverse engineering many of them, but we can not provide the actual
ticket names.

Best regards,

Matthew

**Comment by jaikumarm** [comment]
Aha! no worries. I was able to infer most of them, but not a few.

In any case, very interesting paper and good work. I really liked how you guys balanced the classes with epsilon, I wasn't aware of that and had struggled with it before. 

Am currently using IQfeed to get latest continuous futures data and trying to replicate the results. Am checking in some of the changes in my fork, hopefully it will help someone.
